// Generated by https://quicktype.io

export class Equipment {
    id:                       string;
    equipmentName:            string;
    equipmentDescription:     string;
    equipmentPicture:         string;
    equipmentUseInstructions: string;
    daysBetweenMaintenance:   number;
    maintenanceDescription:   string;
}
